/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2012, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

/* This file was autogenerated from .\nlp.tmLanguage.json (uuid: ) */
/****************************************************************************************
 * IT MIGHT NOT BE PERFECT ...But it's a good start from an existing *.tmlanguage file. *
 * fileTypes                                                                            *
 ****************************************************************************************/

"use strict";

var oop = require("../lib/oop");
var TextHighlightRules = require("./text_highlight_rules").TextHighlightRules;

var NLPHighlightRules = function() {
    // regexp must not have capturing parentheses. Use (?:) instead.
    // regexps are ordered -> the first match is used

    this.$rules = {
        start: [{
            include: "#expression"
        }, {
            token: "keyword.region.nlp",
            regex: /@(?:@)?(?:CHECK|CODE|DECL|MULTI|NODES|PATH|POST|PRE|RULES)\b/
        }, {
            token: "keyword.constants.nlp",
            regex: /\b_ROOT\b/
        }, {
            token: "keyword.other.nlp",
            regex: /\b(?:cap|cout|else|gp|group|if|inc|return|while)\b/,
            caseInsensitive: true
        }, {
            token: "keyword.operator.nlp",
            regex: /\b(?:and|not|or|in|>|<|<>|\/|\|+|-|=)\b/,
            caseInsensitive: true
        }, {
            token: ["text", "text"],
            regex: /([\w_]+)(\s*\()/
        }],
        "#functions-node": [{
            token: "entity.name.function.letter.nlp",
            regex: /\b(?:G|N|S|X|L)\b/
        }],
        "#functions": [{
            token: "entity.name.function.nlp",
            regex: /\b(?:addarg|addattr|addcnode|addconcept|addconval|addnode|addnumval|addstmt|addstrs|addstrval|addsval|addword|arraylength|attrchange|attrexists|attrname|attrtype|attrvals|attrwithval|batchstart|cap|cbuf|closefile|conceptname|conceptpath|conval|cout|coutreset|dballocstmt|dbbindcol|dbclose|dbexec|dbexecstmt|dbfetch|dbfreestmt|dbopen|deaccent|debug|dictfindword|dictfirst|dictgetword|dictnext|down|else|eltnode|excise|exitpass|exittopopup|factorial|fail|fileout|findana|findattr|findattrs|findconcept|findhierconcept|findnode|findphrase|findroot|findvals|findwordpath|firstnode|flt|fltval|fncallstart|fprintgvar|fprintnvar|fprintxvar|fprintvar|gdump|getconcept|getconval|getnumval|getpopupdata|getstrval|getsval|ginc|gp|group|gtolower|guniq|hitconf|if|inc|inheritval|inputrange|inputrangetofile|interactive|kbdumptree|lasteltnode|lastnode|length|lengthr|levenshtein|lextagger|listadd|listnode|LJ|lj|logten|lookup|lowercase|makeconcept|makeparentconcept|makephrase|makestmt|merge|merger|mkdir|movecleft|movecright|movesem|ndump|next|nextattr|nextval|ninc|nodeconcept|nodeowner|noop|num|numrange|numval|openfile|or|pathconcept|percentstr|permuten|phraselength|phraseraw|phrasetext|pncopyvars|pndown|pninsert|pnmakevar|pnname|pnnext|pnprev|pnreplaceval|pnroot|pnsingletdown|pnup|pnvar|pnvarnames|pranchor|prchild|preaction|printvar|pndeletechilds|pnrename|prev|print|printr|prlit|prrange|prtree|prunephrases|prxtree|regexp|regexpi|renameattr|renamechild|renameconcept|renamenode|replaceval|resolveurl|return|returnstmt|rfaaction|rfaactions|rfaarg|rfaargtolist|rfacode|rfaelement|rfaelt|rfaexpr|rfalist|rfalitelt|rfalittoaction|rfalittopair|rfaname|rfanodes|rfanonlit|rfanonlitelt|rfanum|rfaop|rfapair|rfapairs|rfapostunary|rfapres|rfarange|rfarecurse|rfarecurses|rfaregion|rfaregions|rfarule|rfarulelts|rfarulemark|rfarules|rfarulesfile|rfaselect|rfastr|rfasugg|rfaunary|rfavar|rfbarg|rfbdecl|rfbdecls|rightjustifynum|rmattr|rmattrs|rmattrval|rmchild|rmchildren|rmconcept|rmcphrase|rmnode|rmphrase|rmval|rmvals|rmword|sdump|setbase|setlookahead|setunsealed|single|singler|singlex|singlezap|sortconsbyattr|sortchilds|sorthier|sortphrase|sortvals|spellcandidates|spellcorrect|spellword|splice|split|sqlstr|startout|stem|stopout|str|strchar|strchr|strchrcount|strclean|strcontains|strcontainsnocase|strendswith|strequal|strequalnocase|strescape|strunescape|strgreaterthan|strisalpha|strisdigit|strislower|strisupper|strlength|strlessthan|strnotequal|strnotequalnocase|strpiece|strrchr|strspellcandidate|strspellcompare|strstartswith|strsubst|strtolower|strtotitle|strtoupper|strtrim|strval|strwrap|succeed|suffix|system|take|today|topdir|unknown|unpackdirs|up|uppercase|urlbase|urltofile|var|vareq|varfn|varfnarray|varinlist|varne|varstrs|varz|wninit|wnsensestoconcept|wnhypnymstoconcept|while|whilestmt|wordindex|wordpath|writekb|xaddlen|xaddnvar|xdump|xinc|xmlstr|xrename)\b/,
            caseInsensitive: true
        }],
        "#expression": [{
            include: "#rules-region"
        }, {
            include: "#comment"
        }, {
            include: "#string"
        }, {
            include: "#literal"
        }],
        "#rules-region": [{
            token: [
                "variable.rewrite.nlp",
                "text",
                "variable.rewrite-symbol.nlp",
                "text",
                "text"
            ],
            regex: /([_\w]+)(\s*)(?:(\[[^\]]*\]))*(\s*)(<-)/,
            push: [{
                token: "keyword.region.nlp",
                regex: /@@/,
                next: "pop"
            }, {
                include: "#token"
            }, {
                include: "#attributes"
            }, {
                include: "#constant-nodes"
            }, {
                include: "#escaped-char"
            }, {
                include: "#comment-line"
            }]
        }],
        "#attributes": [{
            token: "punctuation.square.open",
            regex: /\[/,
            push: [{
                token: "punctuation.square.close",
                regex: /\]/,
                next: "pop"
            }, {
                include: "#attribute-equals"
            }, {
                include: "#constant-nodes"
            }, {
                include: "#token"
            }, {
                include: "#attribute"
            }, {
                include: "#comment-line"
            }, {
                defaultToken: "meta.rules.rule.attribute.nlp"
            }]
        }],
        "#constant-nodes": [{
            token: "keyword.constants.nlp",
            regex: /\b_(?:xWILD|xNUM|xALPHA|xWHITE|xNIL|xSTART|xEND|xCTRL)\b/
        }],
        "#attribute-equals": [{
            token: [
                "text",
                "text",
                "keyword.equals.nlp",
                "text",
                "punctuation.paren.open"
            ],
            regex: /([_\w]+)(\s*)(=)(\s*)(\()/,
            push: [{
                token: "punctuation.paren.open",
                regex: /\)/,
                next: "pop"
            }, {
                include: "#token"
            }, {
                include: "#attribute"
            }, {
                include: "#constant-nodes"
            }, {
                include: "#escaped-char"
            }]
        }],
        "#attribute": [{
            token: "keyword.attribute.nlp",
            regex: /\b(?:attr|attrs|da|deacc|deaccent|except|excepts|fail|fails|gp|group|layer|layers|look|lookahead|match|matches|max|min|nest|o|one|opt|option|optional|pass|passes|plus|recurse|ren|rename|s|singlet|star|t|tree|trig|trigger|unsealed)\b/,
            caseInsensitive: true
        }],
        "#escaped-char": [{
            token: "constant.character.escape",
            regex: /\\./
        }],
        "#token": [{
            token: "variable.parameter.nlp",
            regex: /_[\w]+\b/
        }],
        "#comment": [{
            include: "#comment-line"
        }, {
            include: "#comment-block"
        }],
        "#comment-line": [{
            token: "comment.line.nlp",
            regex: /#.*$/
        }],
        "#comment-block": [{
            token: "comment.block.begin.nlp",
            regex: /\/\*/,
            push: [{
                token: "comment.block.end.nlp",
                regex: /\*\//,
                next: "pop"
            }, {
                defaultToken: "comment.block.nlp"
            }]
        }],
        "#string": [{
            include: "#qstring-double"
        }],
        "#qstring-double": [{
            token: "string.double.nlp",
            regex: /"/,
            push: [{
                token: "string.double.nlp",
                regex: /\"|[^\\$]$/,
                next: "pop"
            }, {
                include: "#string-character-escape"
            }, {
                defaultToken: "string.double.nlp"
            }]
        }],
        "#string-character-escape": [{
            token: "constant.character.escape.nlp",
            regex: /\\(?:x[\da-fA-F]{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)/
        }],
        "#literal": [{
            include: "#numeric-literal"
        }, {
            include: "#array-literal"
        }],
        "#numeric-literal": [{
            token: "constant.numeric.nlp",
            regex: /\b(?<=[^$])(?:0(?:x|X)[0-9a-fA-F]+|0(?:o|O)[0-7]+|0(?:b|B)(?:0|1)+|[0-9]+(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+(?:\.[0-9]+)?)?)\b/
        }],
        "#array-literal": [{
            token: "meta.brace.square.nlp",
            regex: /\[/,
            push: [{
                token: "meta.brace.square.nlp",
                regex: /\]/,
                next: "pop"
            }, {
                include: "#expression"
            }, {
                defaultToken: "meta.array.literal.nlp"
            }]
        }]
    }
    
    this.normalizeRules();
};

NLPHighlightRules.metaData = {
    scopeName: "source.nlp",
    fileTypes: ["nlp", "pat"],
    name: "NLP"
}


oop.inherits(NLPHighlightRules, TextHighlightRules);

exports.NLPHighlightRules = NLPHighlightRules;