/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2012, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

/* This file was autogenerated from .\tree.tmLanguage.json (uuid: ) */
/****************************************************************************************
 * IT MIGHT NOT BE PERFECT ...But it's a good start from an existing *.tmlanguage file. *
 * fileTypes                                                                            *
 ****************************************************************************************/

"use strict";

var oop = require("../lib/oop");
var TextHighlightRules = require("./text_highlight_rules").TextHighlightRules;

var TreeHighlightRules = function() {
    // regexp must not have capturing parentheses. Use (?:) instead.
    // regexps are ordered -> the first match is used

    this.$rules = {
        start: [{
            include: "#expression"
        }],
        "#expression": [{
            include: "#comment-line"
        }, {
            include: "#rewrites"
        }, {
            include: "#node-name"
        }, {
            include: "#attributes"
        }],
        "#node-name": [{
            token: "keyword.node.tree",
            regex: /^[\s]+[^_\s]+/
        }],
        "#rewrites": [{
            token: "keyword.rewrite.tree",
            regex: /\b_[\w]+\b/
        }],
        "#attributes": [{
            token: "meta.attribute.tree",
            regex: /\[/,
            push: [{
                token: "meta.attribute.tree",
                regex: /\]/,
                next: "pop"
            }, {
                include: "#number"
            }, {
                include: "#literal"
            }, {
                include: "#qstring-double"
            }, {
                defaultToken: "meta.attribute.tree"
            }]
        }],
        "#qstring-double": [{
            token: "string.double.tree",
            regex: /"/,
            push: [{
                token: "string.double.tree",
                regex: /\"|[^\\$]$/,
                next: "pop"
            }, {
                include: "#string-character-escape"
            }, {
                defaultToken: "string.double.tree"
            }]
        }],
        "#string-character-escape": [{
            token: "constant.character.escape.tree",
            regex: /\\(?:x[\da-fA-F]{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)/
        }],
        "#literal": [{
            include: "#numeric-literal"
        }, {
            include: "#types"
        }, {
            include: "#fired"
        }],
        "#number": [{
            token: "constant.numeric.tree",
            regex: /\b[0-9]+\b/
        }],
        "#fired": [{
            token: "keyword.fired.tree",
            regex: /\bfired\b/,
            caseInsensitive: true
        }],
        "#types": [{
            token: "keyword.attribute.tree",
            regex: /\b(?:alpha|ctrl|emoji|node|num|punct|white)\b/,
            caseInsensitive: true
        }],
        "#comment-line": [{
            token: "comment.line.dict",
            regex: /\s*#.*$/
        }]
    }
    
    this.normalizeRules();
};

TreeHighlightRules.metaData = {
    scopeName: "source.tree",
    fileTypes: ["log", "tree"],
    name: "Tree"
}


oop.inherits(TreeHighlightRules, TextHighlightRules);

exports.TreeHighlightRules = TreeHighlightRules;